---
# tasks file for ansible-cis-ubuntu-2204

# ------------------------------------------------------------------------------

- name: "POST | find removed but configured apt packages"
  ansible.builtin.shell: >
    set -o pipefail &&
    dpkg --list | (grep ^rc || true) | tr -s ' ' | cut -d ' ' -f 2
  args:
    executable: "{{ cis_ubuntu2204_shell_executable }}"
  register: apt_removed_packages
  changed_when: false
  tags:
    - post

- name: "POST | perform apt package cleanup"
  ansible.builtin.apt:
    name: "{{ apt_removed_packages.stdout_lines }}"
    state: absent
    purge: true
  changed_when: false
  when:
    - apt_removed_packages is defined
    - apt_removed_packages.stdout_lines is defined
    - apt_removed_packages.stdout_lines | length > 0
    - not ansible_check_mode
  tags:
    - post
