blank_issues_enabled: false
contact_links:
  - name: Report incorrect or missing information on our website
    url: https://mvladislav.online/issues
    about: Our documentation has its own issue tracker. Please report issues with the website there.
  - name: I have a question or need support
    url: https://mvladislav.online/help
    about: We use GitHub for tracking bugs, check our website for resources on getting help.
  - name: Feature Request
    url: https://mvladislav.online/feature-requests
    about: Please use our Community Forum for making feature requests.
  - name: I'm unsure where to go
    url: https://mvladislav.online/join-chat
    about: If you are unsure where to go, then joining our chat is recommended; Just ask!
